image: Visual Studio 2017
init:
  - git config --global core.autocrlf input
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
install:
  # Install OpenGL
  - "powershell ./install-opengl.ps1"

build_script:
  - "powershell ./test-dll.ps1"
on_finish:
  - "powershell ./install-opengl.ps1 uninstall"