image: Visual Studio 2017
init:
  - git config --global core.autocrlf input
install:
  # Install OpenGL
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - ps: $blockRdp = $true;
  - "powershell ./install-opengl.ps1"

build_script:
  - "powershell ./test-dll.ps1"
